/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as IndexRouteImport } from './routes/index'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/logs': typeof LogsRoute
  '/marketplace': typeof MarketplaceRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/logs': typeof LogsRoute
  '/marketplace': typeof MarketplaceRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/logs': typeof LogsRoute
  '/marketplace': typeof MarketplaceRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capabilities'
    | '/chat'
    | '/history'
    | '/logs'
    | '/marketplace'
    | '/servers'
    | '/settings'
    | '/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capabilities'
    | '/chat'
    | '/history'
    | '/logs'
    | '/marketplace'
    | '/servers'
    | '/settings'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/capabilities'
    | '/chat'
    | '/history'
    | '/logs'
    | '/marketplace'
    | '/servers'
    | '/settings'
    | '/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapabilitiesRoute: typeof CapabilitiesRoute
  ChatRoute: typeof ChatRoute
  HistoryRoute: typeof HistoryRoute
  LogsRoute: typeof LogsRoute
  MarketplaceRoute: typeof MarketplaceRoute
  ServersRoute: typeof ServersRoute
  SettingsRoute: typeof SettingsRoute
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapabilitiesRoute: CapabilitiesRoute,
  ChatRoute: ChatRoute,
  HistoryRoute: HistoryRoute,
  LogsRoute: LogsRoute,
  MarketplaceRoute: MarketplaceRoute,
  ServersRoute: ServersRoute,
  SettingsRoute: SettingsRoute,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
